version: '2.21'

services:

  postgres_db:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    command: -p 5432
    expose:
      - 5432
    volumes:
      - ./docker/pg-date:/var/lib/postgresql/data/
    env_file:
      - .env

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  pgadmin_app:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin_container
    ports:
      - 5050:80
    user: "${UID}:${GID}"  
    volumes:
      - ./docker/pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env  
    depends_on:
      - postgres_db

volumes:
  pg-data:
  pgadmin-data: